version: '2'
services:
  servicebot:
    image: servicebot/servicebot
    environment:
      - POSTGRES_DB_PORT
      - POSTGRES_DB_HOST
      - POSTGRES_DB_USER
      - POSTGRES_DB_PASSWORD
      - POSTGRES_DB_NAME
      - PORT=3000
    volumes:
      - upload-data:/usr/src/app/uploads
      - environment-file:/usr/src/app/env
    links:
      - db
    ports:
      - "81:3000"
      - "443:3001"
    command: ["sh", "-c", "node /usr/src/app/bin/wait-for-it.js db 5432  && npm run-script start"]
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
volumes:
  upload-data:
  environment-file:
  db-data:
